WMO_WEATHER_CODE_DE = {
    0: "Wolkenentwicklung nicht beobachtet / nicht sichtbar",
    1: "Wolken lösen sich allgemein auf",
    2: "Unveränderter Bewölkungszustand",
    3: "Wolken bilden sich oder nehmen zu",
    4: "Sicht durch Rauch vermindert",

    5: "Dunst (Haze)",
    6: "Weit verbreiteter Staub in der Luft, nicht durch Wind aufgewirbelt",
    7: "Staub oder Sand durch Wind aufgewirbelt",
    8: "Gut entwickelte Staub- oder Sandwirbel",
    9: "Sand- oder Staubsturm in Sichtweite, nicht am Standort",

    10: "Dunst / feiner Nebel",
    11: "Nebelflecken",
    12: "Durchgehender flacher Nebel",
    13: "Blitze sichtbar, kein Donner hörbar",
    14: "Niederschlag in Sicht, erreicht den Boden nicht",
    15: "Niederschlag in Sicht, erreicht weit entfernt den Boden",
    16: "Niederschlag in Sicht, erreicht nahe den Boden",
    17: "Donner hörbar, kein Niederschlag am Standort",
    18: "Böen",
    19: "Tornado / Wasserhose / Staub- oder Sandsturm in Sicht",

    20: "Nieselregen oder Schneekörner in letzter Stunde",
    21: "Regen in letzter Stunde",
    22: "Schneefall in letzter Stunde",
    23: "Regen und Schnee / Eiskörner in letzter Stunde",
    24: "Gefrierender Nieselregen oder gefrierender Regen in letzter Stunde",
    25: "Regenschauer in letzter Stunde",
    26: "Schneeschauer in letzter Stunde",
    27: "Hagel- oder Eiskornschauer in letzter Stunde",
    28: "Nebel oder Eisnebel",
    29: "Gewitter in der letzten Stunde",

    30: "Leichter oder mäßiger Sand- / Staubsturm, abnehmend",
    31: "Leichter oder mäßiger Sand- / Staubsturm, unverändert",
    32: "Leichter oder mäßiger Sand- / Staubsturm, zunehmend",
    33: "Schwerer Sand- / Staubsturm, abnehmend",
    34: "Schwerer Sand- / Staubsturm, unverändert",
    35: "Schwerer Sand- / Staubsturm, zunehmend",
    36: "Schneeverwehung niedrig",
    37: "Schneeverwehung hoch",
    38: "Schnee durch Wind aufgewirbelt",
    39: "Starke Schneeverwehung",

    40: "Nebel in der Ferne",
    41: "Fleckiger Nebel",
    42: "Nebel, Himmel sichtbar, abnehmend",
    43: "Nebel, Himmel sichtbar, unverändert",
    44: "Nebel, Himmel sichtbar, zunehmend",
    45: "Nebel, Himmel unsichtbar, abnehmend",
    46: "Nebel, Himmel unsichtbar, unverändert",
    47: "Nebel, Himmel unsichtbar, zunehmend",
    48: "Nebel mit Raueisbildung",
    49: "Nebel mit Sichtweite < 50 m",

    50: "Nieselregen, sehr leicht",
    51: "Nieselregen, leicht",
    52: "Nieselregen, mäßig",
    53: "Nieselregen, stark",
    54: "Gefrierender Nieselregen, leicht",
    55: "Gefrierender Nieselregen, mäßig",
    56: "Gefrierender Nieselregen, stark",
    57: "Gefrierender Nieselregen, sehr stark",
    58: "Nieselregen und Regen, leicht",
    59: "Nieselregen und Regen, stark",

    60: "Regen, sehr leicht",
    61: "Regen, leicht",
    62: "Regen, mäßig",
    63: "Regen, stark",
    64: "Gefrierender Regen, leicht",
    65: "Gefrierender Regen, mäßig",
    66: "Gefrierender Regen, stark",
    67: "Gefrierender Regen, sehr stark",
    68: "Schneeregen, leicht",
    69: "Schneeregen, stark",

    70: "Schnee, sehr leicht",
    71: "Schnee, leicht",
    72: "Schnee, mäßig",
    73: "Schnee, stark",
    74: "Eiskörner, leicht",
    75: "Eiskörner, mäßig",
    76: "Eiskörner, stark",
    77: "Schneekörner",
    78: "Eiskristalle",
    79: "Graupel oder Schneekörner",

    80: "Regenschauer, leicht",
    81: "Regenschauer, mäßig",
    82: "Regenschauer, heftig",
    83: "Schauer aus Regen und Schnee, leicht",
    84: "Schauer aus Regen und Schnee, stark",
    85: "Schneeschauer, leicht",
    86: "Schneeschauer, stark",
    87: "Schauer von Eiskörnern, leicht",
    88: "Schauer von Eiskörnern, mäßig oder stark",
    89: "Hagelschauer, leicht",
    90: "Hagelschauer, schwer",

    91: "Gewitter mit Regen, leicht oder mäßig",
    92: "Gewitter mit Schnee, leicht oder mäßig",
    93: "Gewitter mit Hagel, leicht oder mäßig",
    94: "Starkes Gewitter mit Regen",
    95: "Starkes Gewitter (ohne Hagel)",
    96: "Gewitter mit Hagel, leicht oder mäßig",
    97: "Gewitter mit starkem Hagel",
    98: "Gewitter mit Sand- oder Staubsturm",
    99: "Schweres Gewitter mit Hagel"
}
